fix the postinst to include the default postgres port

diff --git a/debian/lavapdu.postinst b/debian/lavapdu.postinst
--- a/debian/lavapdu.postinst
+++ b/debian/lavapdu.postinst
@@ -4,12 +4,18 @@ set -e
 LAVAPDU_USER="pdudaemon"
 LAVAPDU_PASS="pdudaemon"
 LAVAPDU_NAME="lavapdu"
+LAVA_DB_PORT=5432
+
+die() {
+    echo "$1"
+    exit 1
+}
 
 install_database()
 {
     # Create database user, if it doesn't exist
-    if ! su postgres -c "psql \"-c SELECT usename FROM pg_user WHERE usename='$LAVAPDU_USER'\""; then
-        su postgres -c "createuser --no-createdb --encrypted --login --no-superuser --no-createrole --no-password $LAVAPDU_USER"|| "Failed to create database user"
+    if ! su postgres -c "psql \"-c SELECT usename FROM pg_user WHERE usename='$LAVAPDU_USER'\"" | grep "$LAVAPDU_USER"; then
+        su postgres -c "createuser --no-createdb --encrypted --login --no-superuser --no-createrole --no-password --port $LAVA_DB_PORT $LAVAPDU_USER"|| "Failed to create database user"
     fi
 
     # Set a password for our new user
@@ -17,17 +23,17 @@ install_database()
 
     # Create a database for our new user, if it doesn't exist
     if ! su postgres -c "psql -c \"SELECT datname FROM pg_database WHERE datname='$LAVAPDU_NAME'\"" | grep "$LAVAPDU_NAME"; then
-        su postgres -c "createdb --locale=C.UTF-8 --encoding=UTF-8 --owner=$LAVAPDU_USER --template=template0 --no-password $LAVAPDU_NAME" || die "Failed to create a database"
+        su postgres -c "createdb --port $LAVA_DB_PORT --locale=C.UTF-8 --encoding=UTF-8 --owner=$LAVAPDU_USER --template=template0 --no-password $LAVAPDU_NAME" || die "Failed to create a database"
     fi
 }
 
 
-if [ -x "/etc/init.d/lavapdu-listen.init" ]; then
+if [ -x "/etc/init.d/lavapdu-listen" ]; then
     update-rc.d lavapdu-listen defaults >/dev/null
     invoke-rc.d lavapdu-listen start || exit $?
 fi
 
-if [ -x "/etc/init.d/lavapdu-runner.init" ]; then
+if [ -x "/etc/init.d/lavapdu-runner" ]; then
     update-rc.d lavapdu-runner defaults >/dev/null
     invoke-rc.d lavapdu-runner start || exit $?
 fi
