Create the database, if none exists, at install.

diff --git a/debian/lavapdu.postinst b/debian/lavapdu.postinst
--- a/debian/lavapdu.postinst
+++ b/debian/lavapdu.postinst
@@ -1,14 +1,49 @@
 #!/bin/sh
 set -e
 
+LAVAPDU_USER="pdudaemon"
+LAVAPDU_PASS="pdudaemon"
+LAVAPDU_NAME="lavapdu"
+
+install_database()
+{
+    # Create database user, if it doesn't exist
+    if ! su postgres -c "psql \"-c SELECT usename FROM pg_user WHERE usename='$LAVAPDU_USER'\""; then
+        su postgres -c "createuser --no-createdb --encrypted --login --no-superuser --no-createrole --no-password $LAVAPDU_USER"|| "Failed to create database user"
+    fi
+
+    # Set a password for our new user
+    su postgres -c "psql --port $LAVA_DB_PORT --quiet --command=\"ALTER USER \"$LAVAPDU_USER\" WITH PASSWORD '$LAVAPDU_PASS'\"" || die "Failed to set database password"
+
+    # Create a database for our new user, if it doesn't exist
+    if ! su postgres -c "psql -c \"SELECT datname FROM pg_database WHERE datname='$LAVAPDU_NAME'\"" | grep "$LAVAPDU_NAME"; then
+        su postgres -c "createdb --locale=C.UTF-8 --encoding=UTF-8 --owner=$LAVAPDU_USER --template=template0 --no-password $LAVAPDU_NAME" || die "Failed to create a database"
+    fi
+}
+
+
 if [ -x "/etc/init.d/lavapdu-listen.init" ]; then
-	update-rc.d lavapdu-listen defaults >/dev/null
-	invoke-rc.d lavapdu-listen start || exit $?
+    update-rc.d lavapdu-listen defaults >/dev/null
+    invoke-rc.d lavapdu-listen start || exit $?
 fi
 
 if [ -x "/etc/init.d/lavapdu-runner.init" ]; then
-	update-rc.d lavapdu-runner defaults >/dev/null
-	invoke-rc.d lavapdu-runner start || exit $?
+    update-rc.d lavapdu-runner defaults >/dev/null
+    invoke-rc.d lavapdu-runner start || exit $?
 fi
+
+case "$1" in
+    configure)
+        install_database
+    ;;
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
 
 #DEBHELPER#
